name: Stale

on:
  schedule:
  - cron: '00 19 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 7
        days-before-close: 21
        stale-issue-message: 'The issue has been marked as stale, due to the 1 week of inactivity.'
        stale-pr-message: 'The PR has been marked as stale, due to the 3 weeks of inactivity.'
        stale-issue-label: 'stale-issue'
        stale-pr-label: 'stale-pr'
        exempt-issue-labels: 'inprogress'
        labels-to-add-when-unstale: 'revived'
        labels-to-remove-when-stale: 'revived'
        
